/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Tama
 */
public class FormPilih extends javax.swing.JFrame {
    private String userRole;

    /**
     * Creates new form FormPilih
     */
    public FormPilih() {
        initComponents();
        setSize(416,300);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKota = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnKota.setBackground(new java.awt.Color(153, 204, 255));
        btnKota.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btnKota.setText("Tambah Kota");
        btnKota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKota);
        btnKota.setBounds(90, 70, 230, 40);

        btnJadwal.setBackground(new java.awt.Color(153, 204, 255));
        btnJadwal.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btnJadwal.setText("Tambah Jadwal");
        btnJadwal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwal);
        btnJadwal.setBounds(90, 150, 230, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg-tambah-jadwal.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 400, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKotaActionPerformed
        // TODO add your handling code here:
        // Buat instance dari kelas TambahKota
        TambahKota tambahKotaFrame = new TambahKota();

        // Sembunyikan frame saat ini
        this.setVisible(false);

        // Tampilkan frame TambahKota
        tambahKotaFrame.setVisible(true);
    }//GEN-LAST:event_btnKotaActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        // Buat instance dari kelas TiketPesawat
        TiketPesawat tiketPesawat = new TiketPesawat(userRole); // gantilah dengan implementasi yang sesuai

        // Buat instance dari kelas TambahJadwal dengan menyertakan parameter TiketPesawat
        TambahJadwal tambahJadwalFrame = new TambahJadwal(tiketPesawat);

        // Sembunyikan frame saat ini
        this.setVisible(false);

        // Tampilkan frame TambahJadwal
        tambahJadwalFrame.setVisible(true);
    }//GEN-LAST:event_btnJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPilih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKota;
    // End of variables declaration//GEN-END:variables
}
